export {default as Footer} from './Footer'
export {default as Layout} from './Layout'
export {default as Navbar} from './Navbar'
export {default as Banner} from './Banner'
export {default as Section1} from './Section1'
export {default as Section2} from './Section2'
export {default as Section3} from './Section3'
export {default as Newsletter} from './Newsletter'
